### PR TITLE
Should fix the "xx bytes unread" issue

### PR DESCRIPTION
**Pull request by AppleDevelops**

### CODE REVIEW

**Comment by IrishPacks** [comment]
Haven't had this issue at all?

**Comment by AppleDevelops** [comment]
I've had the issue multiple times

**Comment by IrishPacks** [comment]
Screenshot it.

**Comment by IrishPacks** [comment]
Closing, had to clean up things, but I'll take a look into this PR to see if anything is affected. Thanks for submitting!

**Comment by IrishPacks** [comment]
Don't try to do this, you must reset it as the packet won't show otherwise.

**Pull request closed without merging**
